var treeBean = {
	"msg": "加载成功",
	"state": "200",
	"id": "",
	"data": {},
	"datatwo": {},
	"list": [{
		"sysCode": "000.001",
		"subList": [{
			"sysCode": "000.001.001",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇东滩村支部委员会",
			"bianma": "中共卓资县卓资山镇东滩村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78105,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.002",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇东街社区支部委员会 ",
			"bianma": "中共卓资县卓资山镇东街社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78107,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.003",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇南窑子社区支部委员会 ",
			"bianma": "中共卓资县卓资山镇南窑子社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78108,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.004",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇苏计村支部委员会 ",
			"bianma": "中共卓资县卓资山镇苏计社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 4,
			"id": 78109,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.005",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇奎元村支部委员会 ",
			"bianma": "中共卓资县卓资山镇奎元村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78110,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.006",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇新建街社区支部委员会 ",
			"bianma": "中共卓资县卓资山镇新建街社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78111,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.007",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇大庆街社区支部委员会 ",
			"bianma": "中共卓资县卓资山镇大庆街社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78112,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.008",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇山顶村支部委员会 ",
			"bianma": "中共卓资县卓资山镇山顶村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78113,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.009",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇蓝旗村支部委员会 ",
			"bianma": "中共卓资县卓资山镇蓝旗村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78114,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.010",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇马盖图村支部委员会 ",
			"bianma": "中共卓资县卓资山镇马盖图村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 10,
			"id": 78115,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.011",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇岱青村支部委员会 ",
			"bianma": "中共卓资县卓资山镇岱青村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 11,
			"id": 78116,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.012",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇张家卜村支部委员会 ",
			"bianma": "中共卓资县卓资山镇张家卜村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 12,
			"id": 78117,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.013",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇六苏木村支部委员会 ",
			"bianma": "中共卓资县卓资山镇六苏木村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 13,
			"id": 78118,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.014",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇广兴城村支部委员会 ",
			"bianma": "中共卓资县卓资山镇广兴城村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 14,
			"id": 78119,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.015",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇麻迷图村支部委员会 ",
			"bianma": "中共卓资县卓资山镇麻迷图村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 15,
			"id": 78120,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.016",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇新民街社区支部委员会",
			"bianma": "中共卓资县卓资山镇新民街社区支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 16,
			"id": 78121,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.017",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇和平村支部委员会 ",
			"bianma": "中共卓资县卓资山镇和平村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 17,
			"id": 78122,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.018",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇温都花村支部委员会 ",
			"bianma": "中共卓资县卓资山镇温都花村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 18,
			"id": 78123,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.019",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇印堂子村支部委员会 ",
			"bianma": "中共卓资县卓资山镇印堂子村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 19,
			"id": 78124,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.020",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇头号村支部委员会 ",
			"bianma": "中共卓资县卓资山镇头号村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 20,
			"id": 78125,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.021",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇五星村支部委员会 ",
			"bianma": "中共卓资县卓资山镇五星村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 21,
			"id": 78126,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.022",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇机关支部委员会 ",
			"bianma": "中共卓资县卓资山镇机关支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 22,
			"id": 78127,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.023",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇河南社区支部委员会 ",
			"bianma": "中共卓资县卓资山镇河南社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 23,
			"id": 78128,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.024",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇北街社区支部委员会 ",
			"bianma": "中共卓资县卓资山镇北街社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 25,
			"id": 78129,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.025",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇新民街村支部委员会 ",
			"bianma": "中共卓资县卓资山镇新民街村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 26,
			"id": 78130,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.026",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇龙胜社区支部委员会 ",
			"bianma": "中共卓资县卓资山镇龙胜社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 27,
			"id": 78131,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.027",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇中营子坝底村联合支部委员会 ",
			"bianma": "中共卓资县卓资山镇中营子坝底村联合支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 28,
			"id": 78132,
			"parentId": "78104"
		}, {
			"sysCode": "000.001.028",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县卓资山镇福祥社区支部委员会 ",
			"bianma": "中共卓资县卓资山镇福祥社区支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 29,
			"id": 78133,
			"parentId": "78104"
		}],
		"isParent": true,
		"name": "中共卓资山镇委员会",
		"bianma": "中共卓资县卓资山镇委员会",
		"icon": "static/images/department.gif",
		"orderBy": 1,
		"id": 78104,
		"parentId": "228"
	}, {
		"sysCode": "000.002",
		"subList": [{
			"sysCode": "000.002.001",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇碌碡坪村支部委员会",
			"bianma": "中共卓资县旗下营镇碌碡平坪村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78141,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.002",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇油房营坪村支部委员会",
			"bianma": "中共卓资县旗下营镇油房营坪村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78142,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.003",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇城乡管理办公室支部委员会",
			"bianma": "中共卓资县旗下营镇城乡管理办公室支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78143,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.004",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县上高台林场支部委员会",
			"bianma": "中共卓资县上高台林场支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 4,
			"id": 78144,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.005",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇青山村支部委员会",
			"bianma": "中共卓资县旗下营镇青山村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78145,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.006",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇一间房村支部委员会",
			"bianma": "中共卓资县旗下营镇一间房村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78146,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.007",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇机关第一支部委员会",
			"bianma": "中共卓资县旗下营镇机关第一支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78147,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.008",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇蓿麻湾村支部委员会",
			"bianma": "中共卓资县旗下营镇蓿麻湾村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78148,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.009",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇中心医院支部委员会",
			"bianma": "中共卓资县旗下营镇中心医院支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78149,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.010",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇东街社区支部委员会",
			"bianma": "中共卓资县旗下营镇东街社区支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 10,
			"id": 78150,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.011",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇西街社区支部委员会",
			"bianma": "中共卓资县旗下营镇西街社区支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 11,
			"id": 78151,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.012",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇伏虎村支部委员会",
			"bianma": "中共卓资县旗下营镇伏虎村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 12,
			"id": 78152,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.013",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇机关第二支部委员会",
			"bianma": "中共卓资县旗下营镇机关第二支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 13,
			"id": 78153,
			"parentId": "78134"
		}, {
			"sysCode": "000.002.014",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县旗下营镇四道沟村支部委员会",
			"bianma": "中共卓资县旗下营镇四道沟村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 14,
			"id": 78154,
			"parentId": "78134"
		}],
		"isParent": true,
		"name": "中共旗下营镇委员会",
		"bianma": "中共旗下营镇委员会",
		"icon": "static/images/department.gif",
		"orderBy": 2,
		"id": 78134,
		"parentId": "228"
	}, {
		"sysCode": "000.003",
		"subList": [{
			"sysCode": "000.003.001",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇厂汉梁村支部委员会",
			"bianma": "中共卓资县十八台镇厂汉梁村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78198,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.002",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇下营子村支部委员会",
			"bianma": "中共卓资县十八台镇下营子村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78199,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.003",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇机关支部委员会",
			"bianma": "中共卓资县十八台镇机关支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78200,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.004",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇印山湾村支部委员会",
			"bianma": "中共卓资县十八台镇印山湾村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 4,
			"id": 78201,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.005",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇梅力盖图村支部委员会",
			"bianma": "中共卓资县十八台镇梅力盖图村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78202,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.006",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇双此老村支部委员会",
			"bianma": "中共卓资县十八台镇双此老村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78203,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.007",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇八苏木村支部委员会",
			"bianma": "中共卓资县十八台镇八苏木村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78204,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.008",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇脑包洼村支部委员会",
			"bianma": "中共卓资县十八台镇脑包洼村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78205,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.009",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇九苏木村支部委员会",
			"bianma": "中共卓资县十八台镇九苏木村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78206,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.010",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇榆树沟村支部委员会",
			"bianma": "中共卓资县十八台镇榆树沟村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 10,
			"id": 78207,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.011",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇十八台村支部委员会",
			"bianma": "中共卓资县十八台镇十八台村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 11,
			"id": 78208,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.012",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇泉脑子村支部委员会",
			"bianma": "中共卓资县十八台镇泉脑子村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 12,
			"id": 78209,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.013",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇白脑包村支部委员会",
			"bianma": "中共卓资县十八台镇白脑包村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 13,
			"id": 78210,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.014",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇东营子村支部委员会",
			"bianma": "中共卓资县十八台镇东营子村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 14,
			"id": 78211,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.015",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇大湾子村支部委员会",
			"bianma": "中共卓资县十八台镇大湾子村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 15,
			"id": 78212,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.016",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇哈风景村支部委员会",
			"bianma": "中共卓资县十八台镇哈风景村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 16,
			"id": 78213,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.017",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇忽力进图村支部委员会",
			"bianma": "中共卓资县十八台镇忽力进图村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 17,
			"id": 78214,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.019",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇金城洼村支部委员会",
			"bianma": "中共卓资县十八台镇金城洼村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 19,
			"id": 78216,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.020",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇财神梁村支部委员会",
			"bianma": "中共卓资县十八台镇财神梁村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 19,
			"id": 78217,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.021",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇五犊亥村支部委员会",
			"bianma": "中共卓资县十八台镇五犊亥村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 20,
			"id": 78218,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.022",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇哈力盖图村支部委员会",
			"bianma": "中共卓资县十八台镇哈力盖图村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 21,
			"id": 78219,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.023",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇巴音沟村支部委员会",
			"bianma": "中共卓资县十八台镇巴音沟村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 22,
			"id": 78220,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.024",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇黄旗滩村支部委员会",
			"bianma": "中共卓资县十八台镇黄旗滩村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 23,
			"id": 78221,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.025",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇小水沟村支部委员会",
			"bianma": "中共卓资县十八台镇小水沟村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 24,
			"id": 78222,
			"parentId": "78135"
		}, {
			"sysCode": "000.003.026",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县十八台镇朝鲁村支部委员会",
			"bianma": "中共卓资县十八台镇朝鲁村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 25,
			"id": 78223,
			"parentId": "78135"
		}],
		"isParent": true,
		"name": "中共卓资县十八台镇委员会",
		"bianma": "中共卓资县十八台镇委员会",
		"icon": "static/images/department.gif",
		"orderBy": 3,
		"id": 78135,
		"parentId": "228"
	}, {
		"sysCode": "000.004",
		"subList": [{
			"sysCode": "000.004.001",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇丰恒村支部委员会 ",
			"bianma": "中共卓资县梨花镇丰恒村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78185,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.002",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇榆树营村支部委员会 ",
			"bianma": "中共卓资县梨花镇榆树营村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78186,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.003",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇韭菜沟村支部委员会 ",
			"bianma": "中共卓资县梨花镇韭菜沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78187,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.004",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇土城子村支部委员会 ",
			"bianma": "中共卓资县梨花镇土城子村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78188,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.005",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇小土城村支部委员会 ",
			"bianma": "中共卓资县梨花镇小土城村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78189,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.006",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇三道营村支部委员会 ",
			"bianma": "中共卓资县梨花镇三道营村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78190,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.007",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇福胜村支部委员会 ",
			"bianma": "中共卓资县梨花镇福胜村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78191,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.008",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇狮子沟村支部委员会 ",
			"bianma": "中共卓资县梨花镇狮子沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78192,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.009",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇大包沟村支部委员会 ",
			"bianma": "中共卓资县梨花镇大包沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78193,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.010",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇大什字村支部委员会 ",
			"bianma": "中共卓资县梨花镇大什字村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 10,
			"id": 78194,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.011",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇机关支部委员会 ",
			"bianma": "中共卓资县梨花镇机关支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 11,
			"id": 78195,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.012",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇壕赖村联合支部委员会 ",
			"bianma": "中共卓资县梨花镇壕赖村联合支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 12,
			"id": 78196,
			"parentId": "78136"
		}, {
			"sysCode": "000.004.013",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县梨花镇刘广夭村支部委员会 ",
			"bianma": "中共卓资县梨花镇刘广夭村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 13,
			"id": 78197,
			"parentId": "78136"
		}],
		"isParent": true,
		"name": "中共卓资县梨花镇委员会",
		"bianma": "中共卓资县梨花镇委员会",
		"icon": "static/images/department.gif",
		"orderBy": 4,
		"id": 78136,
		"parentId": "228"
	}, {
		"sysCode": "000.005",
		"subList": [{
			"sysCode": "000.005.001",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇快乐村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇快乐村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78173,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.002",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇东房子村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇东房子村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78174,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.003",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇板凳沟村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇板凳沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78175,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.004",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇勇士村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇勇士村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 4,
			"id": 78176,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.005",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇共和村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇共和村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78177,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.006",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇大海村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇大海村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78178,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.007",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇十股地村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇十股地村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78179,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.008",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇什字村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇什字村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78180,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.009",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇召庙村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇召庙村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78181,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.010",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇机关村支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇机关村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 10,
			"id": 78182,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.011",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇巴音永丰联合支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇巴音永丰联合支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 11,
			"id": 78183,
			"parentId": "78137"
		}, {
			"sysCode": "000.005.012",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县巴音锡勒镇西房子风雪湾联合支部委员会 ",
			"bianma": "中共卓资县巴音锡勒镇西房子风雪湾联合支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 12,
			"id": 78184,
			"parentId": "78137"
		}],
		"isParent": true,
		"name": "中共卓资县巴音锡勒镇委员会",
		"bianma": "中共卓资县巴音锡勒镇委员会",
		"icon": "static/images/department.gif",
		"orderBy": 5,
		"id": 78137,
		"parentId": "228"
	}, {
		"sysCode": "000.006",
		"subList": [{
			"sysCode": "000.006.001",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡芦草沟村支部委员会 ",
			"bianma": "中共卓资县大榆树乡芦草沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78155,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.002",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡生态旅游有限公司支部委员会 ",
			"bianma": "中共卓资县大榆树乡生态旅游有限公司支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78156,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.003",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡后房子村支部委员会 ",
			"bianma": "中共卓资县大榆树乡后房子村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78157,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.004",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡河子沟村支部委员会 ",
			"bianma": "中共卓资县大榆树乡河子沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 4,
			"id": 78158,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.005",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡凤凰台村支部委员会 ",
			"bianma": "中共卓资县大榆树乡凤凰台村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78159,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.006",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡大榆树村支部委员会 ",
			"bianma": "中共卓资县大榆树乡大榆树村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78160,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.007",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡大南沟村支部委员会 ",
			"bianma": "中共卓资县大榆树乡大南沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78161,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.008",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡机关支部委员会 ",
			"bianma": "中共卓资县大榆树乡机关支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78162,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.009",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡艾壕洼村支部委员会 ",
			"bianma": "中共卓资县大榆树乡艾壕洼村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78163,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.010",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡阳坡子村支部委员会 ",
			"bianma": "中共卓资县大榆树乡阳坡子村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 10,
			"id": 78164,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.011",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡羊圈湾村支部委员会 ",
			"bianma": "中共卓资县大榆树乡羊圈湾村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 11,
			"id": 78165,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.012",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡小南沟村支部委员会 ",
			"bianma": "中共卓资县大榆树乡小南沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 12,
			"id": 78166,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.013",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡西壕堑村支部委员会 ",
			"bianma": "中共卓资县大榆树乡西壕堑村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 13,
			"id": 78167,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.014",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡狮子沟村支部委员会 ",
			"bianma": "中共卓资县大榆树乡狮子沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 14,
			"id": 78168,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.015",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡麻地卜村支部委员会 ",
			"bianma": "中共卓资县大榆树乡麻地卜村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 15,
			"id": 78169,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.016",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡马莲坝村支部委员会 ",
			"bianma": "中共卓资县大榆树乡马莲坝村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 16,
			"id": 78170,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.017",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡孔督营村支部委员会 ",
			"bianma": "中共卓资县大榆树乡孔督营村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 17,
			"id": 78171,
			"parentId": "78138"
		}, {
			"sysCode": "000.006.018",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县大榆树乡后甘沟村支部委员会 ",
			"bianma": "中共卓资县大榆树乡后甘沟村支部委员会 ",
			"icon": "static/images/department.gif",
			"orderBy": 18,
			"id": 78172,
			"parentId": "78138"
		}],
		"isParent": true,
		"name": "中共卓资县大榆树乡委员会",
		"bianma": "中共卓资县大榆树乡委员会",
		"icon": "static/images/department.gif",
		"orderBy": 6,
		"id": 78138,
		"parentId": "228"
	}, {
		"sysCode": "000.007",
		"subList": [{
			"sysCode": "000.007.001",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡机关支部委员会",
			"bianma": "中共卓资县红召乡机关支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78224,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.002",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡东卜子村支部委员会",
			"bianma": "中共卓资县红召乡东卜子村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78225,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.003",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡官庄子村支部委员会",
			"bianma": "中共卓资县红召乡官庄子村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78226,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.004",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡东风村支部委员会",
			"bianma": "中共卓资县红召乡东风村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 4,
			"id": 78227,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.005",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡下股子村支部委员会",
			"bianma": "中共卓资县红召乡下股子村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78228,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.006",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡寿阳营村支部委员会",
			"bianma": "中共卓资县红召乡寿阳营村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78229,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.007",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡厂汉脑包村支部委员会",
			"bianma": "中共卓资县红召乡厂汉脑包村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78230,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.008",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡红召村支部委员会",
			"bianma": "中共卓资县红召乡红召村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78231,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.009",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡红格图村支部委员会",
			"bianma": "中共卓资县红召乡红格图村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78232,
			"parentId": "78139"
		}, {
			"sysCode": "000.007.010",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县红召乡六号村支部委员会",
			"bianma": "中共卓资县红召乡六号村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 11,
			"id": 78233,
			"parentId": "78139"
		}],
		"isParent": true,
		"name": "中共卓资县红召乡委员会",
		"bianma": "中共卓资县红召乡委员会",
		"icon": "static/images/department.gif",
		"orderBy": 7,
		"id": 78139,
		"parentId": "228"
	}, {
		"sysCode": "000.008",
		"subList": [{
			"sysCode": "000.008.001",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡机关支部委员会",
			"bianma": "中共复兴乡机关支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78234,
			"parentId": "78140"
		}, {
			"sysCode": "000.008.002",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡拐角铺村支部委员会",
			"bianma": "中共复兴乡拐角铺村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78235,
			"parentId": "78140"
		}, {
			"sysCode": "000.008.003",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡罗家营村支部委员会",
			"bianma": "中共复兴乡罗家营村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78236,
			"parentId": "78140"
		}, {
			"sysCode": "000.008.004",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡新德义村支部委员会",
			"bianma": "中共复兴乡新德义村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78237,
			"parentId": "78140"
		}, {
			"sysCode": "000.008.005",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡旧德义村支部委员会",
			"bianma": "中共复兴乡旧德义村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78238,
			"parentId": "78140"
		}, {
			"sysCode": "000.008.006",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡隆胜德村支部委员会",
			"bianma": "中共复兴乡隆胜德村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78239,
			"parentId": "78140"
		}, {
			"sysCode": "000.008.007",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡围子村支部委员会",
			"bianma": "中共复兴乡围子村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78240,
			"parentId": "78140"
		}, {
			"sysCode": "000.008.008",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡上高台村支部委员会",
			"bianma": "中共复兴乡上高台村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78241,
			"parentId": "78140"
		}, {
			"sysCode": "000.008.009",
			"subList": null,
			"isParent": false,
			"name": "中共复兴乡圪塔村支部委员会",
			"bianma": "中共复兴乡圪塔村支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 10,
			"id": 78242,
			"parentId": "78140"
		}],
		"isParent": true,
		"name": "中共卓资县复兴乡委员会",
		"bianma": "中共卓资县复兴乡委员会",
		"icon": "static/images/department.gif",
		"orderBy": 8,
		"id": 78140,
		"parentId": "228"
	}, {
		"sysCode": "000.009",
		"subList": [{
			"sysCode": "000.009.001",
			"subList": [{
				"sysCode": "000.009.001.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县医疗保险管理局机关支部委员会",
				"bianma": "中共卓资县医疗保险管理局机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78293,
				"parentId": "78244"
			}, {
				"sysCode": "000.009.001.002",
				"subList": [{
					"sysCode": "000.009.001.002.005",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县社保局机关支部委员会",
					"bianma": "中共卓资县社保局机关支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 1,
					"id": 78301,
					"parentId": "78294"
				}, {
					"sysCode": "000.009.001.002.004",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县社保局退休第一支部委员会",
					"bianma": "中共卓资县社保局退休第一支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 2,
					"id": 78300,
					"parentId": "78294"
				}, {
					"sysCode": "000.009.001.002.003",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县社保局退休第二支部委员会",
					"bianma": "中共卓资县社保局退休第二支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 3,
					"id": 78299,
					"parentId": "78294"
				}, {
					"sysCode": "000.009.001.002.001",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县社保局退休第三支部委员会",
					"bianma": "中共卓资县社保局退休第三支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 4,
					"id": 78297,
					"parentId": "78294"
				}, {
					"sysCode": "000.009.001.002.002",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县社保局退休第四支部委员会",
					"bianma": "中共卓资县社保局退休第四支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 5,
					"id": 78298,
					"parentId": "78294"
				}],
				"isParent": true,
				"name": "中共卓资县社保局总支部委员会",
				"bianma": "中共卓资县社保局总支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78294,
				"parentId": "78244"
			}, {
				"sysCode": "000.009.001.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县劳动就业服务局机关支部委员会",
				"bianma": "中共卓资县劳动就业服务局机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78295,
				"parentId": "78244"
			}, {
				"sysCode": "000.009.001.004",
				"subList": null,
				"isParent": false,
				"name": "中区卓资县人力资源和社会保障局机关支部委员会",
				"bianma": "中区卓资县人力资源和社会保障局机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78296,
				"parentId": "78244"
			}],
			"isParent": true,
			"name": "中共卓资县人力资源和社会保障局委员会",
			"bianma": "中共卓资县人力资源和社会保障局委员会",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78244,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.002",
			"subList": [{
				"sysCode": "000.009.002.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县十八台八苏木学校支部委员会",
				"bianma": "中共卓资县十八台八苏木学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78302,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县梨花镇福生庄中心学校支部委员会",
				"bianma": "中共卓资县梨花镇福生庄中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78303,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县青少年校外活动中心支部委员会",
				"bianma": "中共卓资县青少年校外活动中心支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78304,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县职业中学支部委员会",
				"bianma": "中共卓资县职业中学支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78305,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.005",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县梨花镇中心学校支部委员会",
				"bianma": "中共卓资县梨花镇中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 5,
				"id": 78306,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.006",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县教师进修学校支部委员会",
				"bianma": "中共卓资县教师进修学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 6,
				"id": 78307,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.007",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县卓资中学支部委员会",
				"bianma": "中共卓资县卓资中学支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 7,
				"id": 78308,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.008",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县复兴中学校支部委员会",
				"bianma": "中共卓资县复兴中学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 8,
				"id": 78309,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.009",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县二中支部委员会",
				"bianma": "中共卓资县二中支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 9,
				"id": 78310,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.010",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县十八台镇梅力盖图中心学校支部委员会",
				"bianma": "中共卓资县十八台镇梅力盖图中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 10,
				"id": 78311,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.011",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县大榆树乡中心学校支部委员会",
				"bianma": "中共卓资县大榆树乡中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 11,
				"id": 78312,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.012",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县大榆树乡后房子中心学校支部委员会",
				"bianma": "中共卓资县大榆树乡后房子中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 12,
				"id": 78313,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.013",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县十八台镇中心学校支部委员会",
				"bianma": "中共卓资县十八台镇中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 13,
				"id": 78314,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.014",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县卓资山镇大庆街小学支部委员会",
				"bianma": "中共卓资县卓资山镇大庆街小学支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 14,
				"id": 78315,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.015",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县教育体育局机关支部委员会",
				"bianma": "中共卓资县教育体育局机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 15,
				"id": 78316,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.016",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县教育体育局教研室支部委员会",
				"bianma": "中共卓资县教育体育局教研室支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 16,
				"id": 78317,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.017",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县卓资山镇北完小支部委员会",
				"bianma": "中共卓资县卓资山镇北完小支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 17,
				"id": 78318,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.018",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县巴音锡勒镇中心学校支部委员会",
				"bianma": "中共卓资县巴音锡勒镇中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 18,
				"id": 78319,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.019",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县幼儿园支部委员会",
				"bianma": "中共卓资县幼儿园支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 19,
				"id": 78320,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.020",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县印堂子中心学校支部委员会",
				"bianma": "中共卓资县印堂子中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 20,
				"id": 78321,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.021",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县六苏木中心学校支部委员会",
				"bianma": "中共卓资县六苏木中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 21,
				"id": 78322,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.022",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县业余体育学校支部委员会",
				"bianma": "中共卓资县业余体育学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 22,
				"id": 78323,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.023",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县红召乡中心学校支部委员会",
				"bianma": "中共卓资县红召乡中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 23,
				"id": 78324,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.024",
				"subList": [{
					"sysCode": "000.009.002.024.001",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县旗下营中学文科支部委员会",
					"bianma": "中共卓资县旗下营中学文科支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 1,
					"id": 78328,
					"parentId": "78325"
				}, {
					"sysCode": "000.009.002.024.002",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县旗下营中学理科支部委员会",
					"bianma": "中共卓资县旗下营中学理科支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 2,
					"id": 78329,
					"parentId": "78325"
				}, {
					"sysCode": "000.009.002.024.003",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县旗下营中学行政支部委员会",
					"bianma": "中共卓资县旗下营中学行政支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 3,
					"id": 78330,
					"parentId": "78325"
				}, {
					"sysCode": "000.009.002.024.004",
					"subList": null,
					"isParent": false,
					"name": "中共卓资县旗下营中学退休支部委员会",
					"bianma": "中共卓资县旗下营中学退休支部委员会",
					"icon": "static/images/department.gif",
					"orderBy": 4,
					"id": 78331,
					"parentId": "78325"
				}],
				"isParent": true,
				"name": "中共卓资县旗下营中学总支部委员会",
				"bianma": "中共卓资县旗下营中学总支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 24,
				"id": 78325,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.025",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县旗下营中心学校支部委员会",
				"bianma": "中共卓资县旗下营中心学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 25,
				"id": 78326,
				"parentId": "78245"
			}, {
				"sysCode": "000.009.002.026",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县卓资山逸夫学校支部委员会",
				"bianma": "中共卓资县卓资山逸夫学校支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 26,
				"id": 78327,
				"parentId": "78245"
			}],
			"isParent": true,
			"name": "中共卓资县教育体育局工作委员会",
			"bianma": "中共卓资县教育体育局工作委员会",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78245,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.003",
			"subList": [{
				"sysCode": "000.009.003.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县人民医院支部委员会",
				"bianma": "中共卓资县人民医院支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78332,
				"parentId": "78246"
			}, {
				"sysCode": "000.009.003.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县妇幼保健计划生育服务中心支部委员会",
				"bianma": "中共卓资县妇幼保健计划生育服务中心支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78333,
				"parentId": "78246"
			}, {
				"sysCode": "000.009.003.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县卫生监督所支部委员会",
				"bianma": "中共卓资县卫生监督所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78334,
				"parentId": "78246"
			}, {
				"sysCode": "000.009.003.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县卫生健康委员会机关党支部",
				"bianma": "中共卓资县卫生健康委员会机关党支部",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78335,
				"parentId": "78246"
			}],
			"isParent": true,
			"name": "中共卓资县卫生健康行业工作委员会",
			"bianma": "中共卓资县卫生健康行业工作委员会",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78246,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.004",
			"subList": [{
				"sysCode": "000.009.004.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局退休支部委员会",
				"bianma": "中共卓资县公安局退休支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78336,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局北片派出所支部委员会",
				"bianma": "中共卓资县公安局北片派出所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78337,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局东片派出所支部委员会",
				"bianma": "中共卓资县公安局东片派出所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78338,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局西片派出所支部委员会",
				"bianma": "中共卓资县公安局西片派出所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78339,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.005",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局南片派出所支部委员会",
				"bianma": "中共卓资县公安局南片派出所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 5,
				"id": 78340,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.006",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局监督管理支部委员会",
				"bianma": "中共卓资县公安局监督管理支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 6,
				"id": 78341,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.007",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局刑警支部委员会",
				"bianma": "中共卓资县公安局刑警支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 7,
				"id": 78342,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.008",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局社会治安综合管理支部委员会",
				"bianma": "中共卓资县公安局社会治安综合管理支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 8,
				"id": 78343,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.009",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局机关综合管理支部委员会",
				"bianma": "中共卓资县公安局机关综合管理支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 9,
				"id": 78344,
				"parentId": "78247"
			}, {
				"sysCode": "000.009.004.010",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公安局反恐处突支部委员会",
				"bianma": "中共卓资县公安局反恐处突支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 10,
				"id": 78345,
				"parentId": "78247"
			}],
			"isParent": true,
			"name": "中共卓资县公安局委员会",
			"bianma": "中共卓资县公安局委员会",
			"icon": "static/images/department.gif",
			"orderBy": 4,
			"id": 78247,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.005",
			"subList": [{
				"sysCode": "000.009.005.001",
				"subList": null,
				"isParent": false,
				"name": "中共国家税务总局卓资县税务局第一支部委员会",
				"bianma": "中共国家税务总局卓资县税务局第一支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78346,
				"parentId": "78248"
			}, {
				"sysCode": "000.009.005.002",
				"subList": null,
				"isParent": false,
				"name": "中共国家税务总局卓资县税务局第二支部委员会",
				"bianma": "中共国家税务总局卓资县税务局第二支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78347,
				"parentId": "78248"
			}],
			"isParent": true,
			"name": "中共国家税务总局卓资县税务局委员会",
			"bianma": "中共国家税务总局卓资县税务局委员会",
			"icon": "static/images/department.gif",
			"orderBy": 5,
			"id": 78248,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.006",
			"subList": [{
				"sysCode": "000.009.006.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县纪委监委机关第一支部委员会",
				"bianma": "中共卓资县纪委监委机关第一支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78348,
				"parentId": "78249"
			}, {
				"sysCode": "000.009.006.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县纪委监委机关第二支部委员会",
				"bianma": "中共卓资县纪委监委机关第二支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78349,
				"parentId": "78249"
			}, {
				"sysCode": "000.009.006.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县纪委监委派驻纪检监察组支部委员会",
				"bianma": "中共卓资县纪委监委派驻纪检监察组支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78350,
				"parentId": "78249"
			}, {
				"sysCode": "000.009.006.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县委巡察办支部委员会",
				"bianma": "中共卓资县委巡察办支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78351,
				"parentId": "78249"
			}],
			"isParent": true,
			"name": "中共卓资县纪委监委总支委员会",
			"bianma": "中共卓资县纪委监委总支委员会",
			"icon": "static/images/department.gif",
			"orderBy": 6,
			"id": 78249,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.007",
			"subList": [{
				"sysCode": "000.009.007.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县人大办第一支部委员会",
				"bianma": "中共卓资县人大办第一支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78352,
				"parentId": "78250"
			}, {
				"sysCode": "000.009.007.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县人大办第二支部委员会",
				"bianma": "中共卓资县人大办第二支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78353,
				"parentId": "78250"
			}],
			"isParent": true,
			"name": "中共卓资县人大办总支部委员会",
			"bianma": "中共卓资县人大办总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 7,
			"id": 78250,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.008",
			"subList": [{
				"sysCode": "000.009.008.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县民政局殡葬管理所支部委员会",
				"bianma": "中共卓资县民政局殡葬管理所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78354,
				"parentId": "78251"
			}, {
				"sysCode": "000.009.008.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县民政局机关支部委员会",
				"bianma": "中共卓资县民政局机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78355,
				"parentId": "78251"
			}],
			"isParent": true,
			"name": "中共卓资县民政局总支部委员会",
			"bianma": "中共卓资县民政局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 8,
			"id": 78251,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.009",
			"subList": [{
				"sysCode": "000.009.009.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县交通运输局支部委员会",
				"bianma": "中共卓资县交通运输局支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78356,
				"parentId": "78252"
			}, {
				"sysCode": "000.009.009.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县公路管理段支部委员会",
				"bianma": "中共卓资县公路管理段支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78357,
				"parentId": "78252"
			}],
			"isParent": true,
			"name": "中共卓资县交通运输局总支部委员会",
			"bianma": "中共卓资县交通运输局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 9,
			"id": 78252,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.010",
			"subList": [{
				"sysCode": "000.009.010.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县财政局第一支部委员会",
				"bianma": "中共卓资县财政局第一支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78358,
				"parentId": "78253"
			}, {
				"sysCode": "000.009.010.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县财政局第二支部委员会",
				"bianma": "中共卓资县财政局第二支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78359,
				"parentId": "78253"
			}],
			"isParent": true,
			"name": "中共卓资县财政局总支部委员会",
			"bianma": "中共卓资县财政局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 10,
			"id": 78253,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.011",
			"subList": [{
				"sysCode": "000.009.011.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县林业和草原局造林站支部委员会",
				"bianma": "中共卓资县林业和草原局造林站支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78360,
				"parentId": "78254"
			}, {
				"sysCode": "000.009.011.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县林业和草原局种苗站支部委员会",
				"bianma": "中共卓资县林业和草原局种苗站支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78361,
				"parentId": "78254"
			}, {
				"sysCode": "000.009.011.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县林业和草原局机关支部委员会",
				"bianma": "中共卓资县林业和草原局机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78362,
				"parentId": "78254"
			}, {
				"sysCode": "000.009.011.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县森林公安局支部委员会",
				"bianma": "中共卓资县森林公安局支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78363,
				"parentId": "78254"
			}, {
				"sysCode": "000.009.011.005",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县保安林场支部委员会",
				"bianma": "中共卓资县保安林场支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 5,
				"id": 78364,
				"parentId": "78254"
			}],
			"isParent": true,
			"name": "中共卓资县林业和草原局总支部委员会",
			"bianma": "中共卓资县林业和草原局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 11,
			"id": 78254,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.012",
			"subList": [{
				"sysCode": "000.009.012.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县工商质量技术监督管理局新区工商所支部委员会",
				"bianma": "中共卓资县工商质量技术监督管理局新区工商所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78365,
				"parentId": "78255"
			}, {
				"sysCode": "000.009.012.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县工商质量技术监督管理局卓资山工商所支部委员会",
				"bianma": "中共卓资县工商质量技术监督管理局卓资山工商所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78366,
				"parentId": "78255"
			}, {
				"sysCode": "000.009.012.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县工商质量技术监督管理局质监机关支部委员会",
				"bianma": "中共卓资县工商质量技术监督管理局质监机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78367,
				"parentId": "78255"
			}, {
				"sysCode": "000.009.012.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县工商质量技术监督管理局巴音锡勒镇支部委员会",
				"bianma": "中共卓资县工商质量技术监督管理局巴音锡勒镇支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78368,
				"parentId": "78255"
			}, {
				"sysCode": "000.009.012.005",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县工商质量技术监督管理局工商机关支部委员会",
				"bianma": "中共卓资县工商质量技术监督管理局工商机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 6,
				"id": 78369,
				"parentId": "78255"
			}, {
				"sysCode": "000.009.012.006",
				"subList": null,
				"isParent": false,
				"name": "中共内蒙古华隆农特电子商务有限公司支部",
				"bianma": "中共内蒙古华隆农特电子商务有限公司支部",
				"icon": "static/images/department.gif",
				"orderBy": 7,
				"id": 78370,
				"parentId": "78255"
			}],
			"isParent": true,
			"name": "中共卓资县市场监督管理局总支部委员会",
			"bianma": "中共卓资县民市场监督管理局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 12,
			"id": 78255,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.013",
			"subList": [{
				"sysCode": "000.009.013.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县人民法院法庭支部委员会",
				"bianma": "中共卓资县人民法院法庭支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78371,
				"parentId": "78256"
			}, {
				"sysCode": "000.009.013.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县人民法院机关支部委员会",
				"bianma": "中共卓资县人民法院机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78372,
				"parentId": "78256"
			}, {
				"sysCode": "000.009.013.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县人民法院离退休支部委员会",
				"bianma": "中共卓资县人民法院离退休支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78373,
				"parentId": "78256"
			}],
			"isParent": true,
			"name": "中共卓资县人民法院总支部委员会",
			"bianma": "中共卓资县人民法院总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 13,
			"id": 78256,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.014",
			"subList": [{
				"sysCode": "000.009.014.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县民农牧和科技局机关支部委员会",
				"bianma": "中共卓资县民农牧和科技局机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78374,
				"parentId": "78257"
			}, {
				"sysCode": "000.009.014.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县种子管理站支部委员会",
				"bianma": "中共卓资县种子管理站支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78375,
				"parentId": "78257"
			}, {
				"sysCode": "000.009.014.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县农业技术推广站支部委员会",
				"bianma": "中共卓资县农业技术推广站支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78376,
				"parentId": "78257"
			}, {
				"sysCode": "000.009.014.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县兽医局支部委员会",
				"bianma": "中共卓资县兽医局支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78377,
				"parentId": "78257"
			}],
			"isParent": true,
			"name": "中共卓资县民农牧和科技局总支部委员会",
			"bianma": "中共卓资县民农牧和科技局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 14,
			"id": 78257,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.015",
			"subList": [{
				"sysCode": "000.009.015.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县住建局机关一支部委员会",
				"bianma": "中共卓资县住建局机关一支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78378,
				"parentId": "78258"
			}, {
				"sysCode": "000.009.015.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县住建局机关二支部委员会",
				"bianma": "中共卓资县住建局机关二支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78379,
				"parentId": "78258"
			}, {
				"sysCode": "000.009.015.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县房产管理局支部委员会",
				"bianma": "中共卓资县房产管理局支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78380,
				"parentId": "78258"
			}, {
				"sysCode": "000.009.015.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县自来水公司支部委员会",
				"bianma": "中共卓资县自来水公司支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78381,
				"parentId": "78258"
			}, {
				"sysCode": "000.009.015.005",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县房屋征收管理办公室支部委员会",
				"bianma": "中共卓资县房屋征收管理办公室支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 5,
				"id": 78382,
				"parentId": "78258"
			}],
			"isParent": true,
			"name": "中共卓资县住房和城乡建设局总支部委员会",
			"bianma": "中共卓资县住房和城乡建设局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 15,
			"id": 78258,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.016",
			"subList": [{
				"sysCode": "000.009.016.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县水利局机关支部委员会",
				"bianma": "中共卓资县水利局机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78383,
				"parentId": "78259"
			}, {
				"sysCode": "000.009.016.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县水利局水土保持工作站支部委员会",
				"bianma": "中共卓资县水利局水土保持工作站支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78384,
				"parentId": "78259"
			}, {
				"sysCode": "000.009.016.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县水利局水政监察大队支部委员会",
				"bianma": "中共卓资县水利局水政监察大队支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78385,
				"parentId": "78259"
			}, {
				"sysCode": "000.009.016.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县水利局离退休支部委员会",
				"bianma": "中共卓资县水利局离退休支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78386,
				"parentId": "78259"
			}, {
				"sysCode": "000.009.016.005",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县水利局水利水管支部委员会",
				"bianma": "中共卓资县水利局水利水管支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 5,
				"id": 78387,
				"parentId": "78259"
			}],
			"isParent": true,
			"name": "中共卓资县水利局总支部委员会",
			"bianma": "中共卓资县水利局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 16,
			"id": 78259,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.017",
			"subList": [{
				"sysCode": "000.009.017.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县文化旅游新闻出版广电局旅游支部委员会",
				"bianma": "中共卓资县文化旅游新闻出版广电局旅游支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78404,
				"parentId": "78260"
			}, {
				"sysCode": "000.009.017.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县文化旅游新闻出版广电局文化支部委员会",
				"bianma": "中共卓资县文化旅游新闻出版广电局文化支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78405,
				"parentId": "78260"
			}, {
				"sysCode": "000.009.017.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县文化旅游新闻出版广电局广电支部委员会",
				"bianma": "中共卓资县文化旅游新闻出版广电局广电支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78406,
				"parentId": "78260"
			}, {
				"sysCode": "000.009.017.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县文化旅游新闻出版广电局电影公司支部委员会",
				"bianma": "中共卓资县文化旅游新闻出版广电局电影公司支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78407,
				"parentId": "78260"
			}, {
				"sysCode": "000.009.017.005",
				"subList": null,
				"isParent": false,
				"name": "中共内蒙古广播电视网络集团有限公司卓资分公司支部委员会",
				"bianma": "中共内蒙古广播电视网络集团有限公司卓资分公司支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 5,
				"id": 78408,
				"parentId": "78260"
			}],
			"isParent": true,
			"name": "中共卓资县文化和旅游局总支部委员会",
			"bianma": "中共卓资县文化和旅游局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 17,
			"id": 78260,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.018",
			"subList": [{
				"sysCode": "000.009.018.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县百货针纺公司支部",
				"bianma": "中共卓资县百货针纺公司支部",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78396,
				"parentId": "78261"
			}, {
				"sysCode": "000.009.018.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县第二建筑安装工程有限责任公司支部",
				"bianma": "中共卓资县第二建筑安装工程有限责任公司支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78397,
				"parentId": "78261"
			}, {
				"sysCode": "000.009.018.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资蒙银村镇银行支部委员会",
				"bianma": "中共卓资蒙银村镇银行支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78398,
				"parentId": "78261"
			}, {
				"sysCode": "000.009.018.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县永利绿色科技有限责任公司支部",
				"bianma": "中共卓资县永利绿色科技有限责任公司支部",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78399,
				"parentId": "78261"
			}, {
				"sysCode": "000.009.018.005",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县宾馆支部",
				"bianma": "中共卓资县宾馆支部",
				"icon": "static/images/department.gif",
				"orderBy": 5,
				"id": 78400,
				"parentId": "78261"
			}, {
				"sysCode": "000.009.018.006",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县第一建筑安装有限责任公司支部",
				"bianma": "中共卓资县第一建筑安装有限责任公司支部",
				"icon": "static/images/department.gif",
				"orderBy": 6,
				"id": 78401,
				"parentId": "78261"
			}, {
				"sysCode": "000.009.018.007",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县晋宏酒楼支部委员会",
				"bianma": "中共卓资县晋宏酒楼支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 7,
				"id": 78402,
				"parentId": "78261"
			}, {
				"sysCode": "000.009.018.008",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县工商业联合会机关支部委员会",
				"bianma": "中共卓资县工商业联合会机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 8,
				"id": 78403,
				"parentId": "78261"
			}],
			"isParent": true,
			"name": "中共卓资县工商业联合会总支部委员会",
			"bianma": "中共卓资县工商业联合会总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 18,
			"id": 78261,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.019",
			"subList": [{
				"sysCode": "000.009.019.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资县工业和信息化局支部委员会",
				"bianma": "中共卓资县工业和信息化局支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78395,
				"parentId": "78262"
			}],
			"isParent": true,
			"name": "中共卓资县工业和信息化局总支部委员会",
			"bianma": "中共卓资县工业和信息化局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 19,
			"id": 78262,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.020",
			"subList": [{
				"sysCode": "000.009.020.001",
				"subList": null,
				"isParent": false,
				"name": "中共卓资供电分局安装分公司支部委员会",
				"bianma": "中共卓资供电分局安装分公司支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78388,
				"parentId": "78263"
			}, {
				"sysCode": "000.009.020.002",
				"subList": null,
				"isParent": false,
				"name": "中共卓资供电分局离退休支部委员会",
				"bianma": "中共卓资供电分局离退休支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78389,
				"parentId": "78263"
			}, {
				"sysCode": "000.009.020.003",
				"subList": null,
				"isParent": false,
				"name": "中共卓资供电分局生产支部委员会",
				"bianma": "中共卓资供电分局生产支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78390,
				"parentId": "78263"
			}, {
				"sysCode": "000.009.020.004",
				"subList": null,
				"isParent": false,
				"name": "中共卓资供电分局生产支部委员会",
				"bianma": "中共卓资供电分局生产支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 4,
				"id": 78391,
				"parentId": "78263"
			}, {
				"sysCode": "000.009.020.005",
				"subList": null,
				"isParent": false,
				"name": "中共卓资供电分局供电所支部委员会",
				"bianma": "中共卓资供电分局供电所支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 5,
				"id": 78392,
				"parentId": "78263"
			}, {
				"sysCode": "000.009.020.006",
				"subList": null,
				"isParent": false,
				"name": "中共卓资供电分局行政支部委员会",
				"bianma": "中共卓资供电分局行政支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 6,
				"id": 78393,
				"parentId": "78263"
			}, {
				"sysCode": "000.009.020.007",
				"subList": null,
				"isParent": false,
				"name": "中共卓资供电分局营销支部委员会",
				"bianma": "中共卓资供电分局营销支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 7,
				"id": 78394,
				"parentId": "78263"
			}],
			"isParent": true,
			"name": "中共乌兰察布电业局卓资供电分局总支部委员会",
			"bianma": "中共乌兰察布电业局卓资供电分局总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 20,
			"id": 78263,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.021",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县委员会办公室支部委员会",
			"bianma": "中共卓资县委员会办公室支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 21,
			"id": 78264,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.022",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县委员会保密机要局支部委员会",
			"bianma": "中共卓资县委员会保密机要局支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 22,
			"id": 78265,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.023",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县人民政府办公室支部委员会",
			"bianma": "中共卓资县人民政府办公室支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 23,
			"id": 78266,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.024",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县政协办公室支部委员会",
			"bianma": "中共卓资县政协办公室支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 24,
			"id": 78267,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.025",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县委组织部机关支部委员会",
			"bianma": "中共卓资县委组织部机关支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 25,
			"id": 78268,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.026",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县委宣传部支部委员会",
			"bianma": "中共卓资县委宣传部支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 26,
			"id": 78269,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.027",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县政法委支部委员会",
			"bianma": "中共卓资县政法委支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 27,
			"id": 78270,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.028",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县委统战部支部委员会",
			"bianma": "中共卓资县委统战部支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 28,
			"id": 78271,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.029",
			"subList": null,
			"isParent": false,
			"name": "中共共青团卓资县委员会支部",
			"bianma": "中共共青团卓资县委员会支部",
			"icon": "static/images/department.gif",
			"orderBy": 29,
			"id": 78272,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.030",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县妇女联合会支部",
			"bianma": "中共卓资县妇女联合会支部",
			"icon": "static/images/department.gif",
			"orderBy": 30,
			"id": 78273,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.031",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县机构编制委员会办公室支部委员会",
			"bianma": "中共卓资县机构编制委员会办公室支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 31,
			"id": 78274,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.032",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县残疾人联合会支部委员会",
			"bianma": "中共卓资县残疾人联合会支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 32,
			"id": 78275,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.033",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县委党校机关支部委员会",
			"bianma": "中共卓资县委党校机关支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 33,
			"id": 78276,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.034",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县应急管理局支部委员会",
			"bianma": "中共卓资县应急管理局支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 34,
			"id": 78277,
			"parentId": "78243"
		}, {
			"sysCode": "000.009.035",
			"subList": null,
			"isParent": false,
			"name": "中共卓资县信访局支部委员会",
			"bianma": "中共卓资县信访局支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 35,
			"id": 78278,
			"parentId": "78243"
		}],
		"isParent": true,
		"name": "中共卓资县直属机关委员会",
		"bianma": "中共卓资县直属机关委员会",
		"icon": "static/images/department.gif",
		"orderBy": 9,
		"id": 78243,
		"parentId": "228"
	}, {
		"sysCode": "000.010",
		"subList": [{
			"sysCode": "000.010.001",
			"subList": null,
			"isParent": false,
			"name": "中共内蒙古中能天然气有限公司委员会",
			"bianma": "中共内蒙古中能天然气有限公司委员会",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78280,
			"parentId": "78279"
		}, {
			"sysCode": "000.010.002",
			"subList": null,
			"isParent": false,
			"name": "中区内蒙古巴迪化工科技有限公司支部",
			"bianma": "中区内蒙古巴迪化工科技有限公司支部",
			"icon": "static/images/department.gif",
			"orderBy": 2,
			"id": 78281,
			"parentId": "78279"
		}, {
			"sysCode": "000.010.003",
			"subList": [{
				"sysCode": "000.010.003.001",
				"subList": null,
				"isParent": false,
				"name": "中共内蒙古伊东集团东兴化工有限责任公司机关支部委员会",
				"bianma": "中共内蒙古伊东集团东兴化工有限责任公司机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78283,
				"parentId": "78282"
			}, {
				"sysCode": "000.010.003.002",
				"subList": null,
				"isParent": false,
				"name": "中共内蒙古伊东集团东兴化工有限责任公司电石支部委员会",
				"bianma": "中共内蒙古伊东集团东兴化工有限责任公司电石支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78284,
				"parentId": "78282"
			}, {
				"sysCode": "000.010.003.003",
				"subList": null,
				"isParent": false,
				"name": "中共内蒙古伊东集团东兴化工有限责任公司生产支部委员会",
				"bianma": "中共内蒙古伊东集团东兴化工有限责任公司生产支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78285,
				"parentId": "78282"
			}],
			"isParent": true,
			"name": "中共内蒙古伊东集团东兴化工有限责任公司总支部委员会",
			"bianma": "中共内蒙古伊东集团东兴化工有限责任公司总支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 3,
			"id": 78282,
			"parentId": "78279"
		}, {
			"sysCode": "000.010.004",
			"subList": null,
			"isParent": false,
			"name": "中共内蒙古旗下营工业区管理委员会机关支部委员会",
			"bianma": "中共内蒙古旗下营工业区管理委员会机关支部委员会",
			"icon": "static/images/department.gif",
			"orderBy": 4,
			"id": 78286,
			"parentId": "78279"
		}],
		"isParent": true,
		"name": "中共内蒙古旗下营工业区工作委员会",
		"bianma": "中共内蒙古旗下营工业区工作委员会",
		"icon": "static/images/department.gif",
		"orderBy": 10,
		"id": 78279,
		"parentId": "228"
	}, {
		"sysCode": "000.011",
		"subList": [{
			"sysCode": "000.011.001",
			"subList": [{
				"sysCode": "000.011.001.001",
				"subList": null,
				"isParent": false,
				"name": "中共内蒙古中西矿业有限公司金川支部委员会",
				"bianma": "中共内蒙古中西矿业有限公司金川支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 1,
				"id": 78290,
				"parentId": "78289"
			}, {
				"sysCode": "000.011.001.002",
				"subList": null,
				"isParent": false,
				"name": "中共内蒙古中西矿业有限公司选矿厂支部委员会",
				"bianma": "中共内蒙古中西矿业有限公司选矿厂支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 2,
				"id": 78291,
				"parentId": "78289"
			}, {
				"sysCode": "000.011.001.003",
				"subList": null,
				"isParent": false,
				"name": "中共内蒙古中西矿业有限公司机关支部委员会",
				"bianma": "中共内蒙古中西矿业有限公司机关支部委员会",
				"icon": "static/images/department.gif",
				"orderBy": 3,
				"id": 78292,
				"parentId": "78289"
			}],
			"isParent": true,
			"name": "中共内蒙古中西矿业有限公司委员会",
			"bianma": "中共内蒙古中西矿业有限公司委员会",
			"icon": "static/images/department.gif",
			"orderBy": 1,
			"id": 78289,
			"parentId": "78287"
		}],
		"isParent": true,
		"name": "中共卓资县非公经济和社会组织工作委员会",
		"bianma": "中共卓资县非公经济和社会组织工作委员会",
		"icon": "static/images/department.gif",
		"orderBy": 11,
		"id": 78287,
		"parentId": "228"
	}, {
		"sysCode": "000.012",
		"subList": null,
		"isParent": false,
		"name": "党组",
		"bianma": "党组",
		"icon": "static/images/department.gif",
		"orderBy": 12,
		"id": 78288,
		"parentId": "228"
	}]
};
export default treeBean;
